name: Catalog

permissions: {}

on:
  workflow_dispatch:
    inputs:
      appName:
        description: "NR1 Nerdpack Name"
        required: true
      version:
        description: "Version to update"
        required: true
      ref:
        description: "Commit SHA to update the submodule to"
        required: true
      user:
        description: "User who initiated the deployment"
        required: true
      action:
        description: "Action to take with submodule. Possible values: add, update"
        required: true
        default: "update"
      url:
        description: "If action == `add`, must supply URL of repo"
        required: false
jobs:
  job-check-workflow-dispatch-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "appName: $APP_NAME"
          echo "version: $VERSION"
          echo "ref: $REF"
          echo "user: $USER"
          echo "action: $ACTION"
          echo "url: $URL"
        env:
          APP_NAME: ${{ github.event.inputs.appName }}
          VERSION: ${{ github.event.inputs.version }}
          REF: ${{ github.event.inputs.ref }}
          USER: ${{ github.event.inputs.user }}
          ACTION: ${{ github.event.inputs.action }}
          URL: ${{ github.event.inputs.url }}

  job-trigger-catalog-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke nr1-catalog PR workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Generate Catalog PR
          repo: newrelic/nr1-catalog
          token: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
          ref: master
          inputs: '{ "appName": ${{ toJSON(github.event.inputs.appName) }}, "version": ${{ toJSON(github.event.inputs.version) }}, "ref": ${{ toJSON(github.event.inputs.ref) }}, "user": ${{ toJSON(github.event.inputs.user) }}, "action": ${{ toJSON(github.event.inputs.action) }}, "url": ${{ toJSON(github.event.inputs.url) }} }'
